# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voca_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('info', models.TextField(blank=True, max_length=1000, null=True)),
                ('joborein', models.TextField(blank=True, max_length=800, null=True)),
                ('firm', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('pspage_id', models.IntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('position_name', models.CharField(blank=True, max_length=15, null=True)),
                ('univs_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'voca_site_search_view_combine',
                'managed': False,
            },
        ),
    ]
